version: "3.7"
services:
  auth-api-key:
    build:
      dockerfile: dockerfile
      context: .
    image: auth-api-key-service_auth-api-key:latest
    environment:
      ADMIN_PASSWD: /run/secrets/adm_passwd
    restart: always
    ports:
      - 8080:8080
    volumes:
      - auth-store:/usr/src/app/keystore
    secrets:
      - adm_passwd
secrets:
  adm_passwd:
    external: true
volumes:
  auth-store:
networks:
  default:
