version: "3.7"
services:
  auth-api-key:
    build:
      dockerfile: dockerfile
      context: .
    environment:
      ADMIN_PASSWD: /run/secrets/ADMIN_PASSWD
    restart: always
    ports:
      - 8080:8080
    volumes:
      - auth-store:/usr/src/app/keystore
secrets:
  ADMIN_PASSWD:
    external: true
volumes:
  auth-store:
networks:
  default:
